In [2]:
from load_data import find_outliers, melt_demand, load_demand_raw, load_demand

find_outliers(melt_demand(load_demand_raw()))

                      store       date  pallets
1654  Four Square Ellerslie 2026-06-03       40
2078  Pak 'n Save Henderson 2026-06-10      120

In [7]:
demand_df = load_demand()

display(demand_df[(demand_df["store"] == "Four Square Ellerslie") & (demand_df["date"] == "2026-06-03")])
display(demand_df[(demand_df["store"] == "Pak 'n Save Henderson") & (demand_df["date"] == "2026-06-10")])

                      store       date  pallets
1654  Four Square Ellerslie 2026-06-03        4

                      store       date  pallets
2078  Pak 'n Save Henderson 2026-06-10       12